# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmvnorm <- function(mean, Precision) {
    .Call(`_MVBart_rmvnorm`, mean, Precision)
}

rlgam <- function(shape) {
    .Call(`_MVBart_rlgam`, shape)
}

rcpparma_hello_world <- function() {
    .Call(`_MVBart_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_MVBart_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_MVBart_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_MVBart_rcpparma_bothproducts`, x)
}

